### ISSUE TITLE
Update to use snake-case variables

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform-terraform-s3-bucket#29]
We have a policy of using snake-case for all terraform variable names.

This module uses a lot of hyphenated variables. Modify it to use snake case variables instead.

NB: This will require updating a lot of existing s3.tf files in the environments repository.

related to https://github.com/ministryofjustice/cloud-platform/issues/2230

**Comment by jakemulley** [comment]
Closed in #73.
